os: "-linux"
dist: xenial
language: python
script:
- python -m pytest -v
deploy:
  api_key:
    secure: alUgwNAvz8pyZ+1ZzRcRrP1Fg1quwkoxz8DKsMlTeUmwDDiKF6j+8GhPanIklSH8UEkAmWYxuJ70si80HcPHi3pCXAzxjQrf27/5s9sbV8MFSZ1XciNKFa/iwmhEzDuvjCHLxUNwlz512oHJUS9VVMGerZPV08xhqzLW4+eqd1ASOPa6kXNqtHkuVL9juII6KwBVIC9NHT9p3zQx9tH9ZDxEFfBTVhDrx32bzVRSNfyjRGFkOwdmORsEwrhfGdExtad2oh2MNGAaLuR00JC6I4aZl+IvPMXjvG+pHATbY9OPV2ncPHeBE4SlJjnwAC1ln5qSh4qqtA1PZCwSG4nc3NJwrWis+tQon7BkdYZ4KN58G/9kFIjQ1HStEAwcJXdWAtJ3ZSr5jcGwXImE5aMBYJVoD3FYaT7EjiUbEX2tY7gBLOkr2Monju+Keme16rjunVMDnIyQYxwpZ0up1VgvEW2XY9fpBDeja7KMjlpN8T2Gj5E4BIKVe2fkZzHXRbeH6SYsHSQ3OZPKwlq5fLUD9MfdEnJAuUrDFDZnqoTWcgdhwtelZ1A+e5Z77YmfUl4shLd3S7c86tjEwFl8p9B9jX+ia2DJamM9IAbrCW3c3xMsSZeyMoOiiVGpq/H3+InLWBdbEkdhq4jye5ntfGdBPv/ztME1sYy1jTsVocDXapk=
